export const productList = [
  {
    id: 1,
    name: 'Chess Tournament №7 Madon',
    image: './images/chess-madon.png',
    rating: 4,
    originalPrice: '120.00',
    discountedPrice: '80.00',
    new: true,
  },
  {
    id: 2,
    name: 'Chess pieces Staunton №5',
    image: './images/chess-staunton.png',
    rating: 5,
    originalPrice: '45.00',
    discountedPrice: '35.00',
  },
  {
    id: 3,
    name: 'Chess clock DGT 2010',
    image: './images/clock-dgt.png',
    rating: 5,
    originalPrice: '75.00',
    discountedPrice: '60.00',
    new: true,
  },
  {
    id: 4,
    name: 'Chess Olympic Madon',
    image: './images/chess-olympic.png',
    rating: 5,
    originalPrice: '140.00',
    discountedPrice: '100.00',
  },
  {
    id: 5,
    name: 'Chess clock DGT 3000',
    image: './images/clock-dgt-3000.png',
    rating: 5,
    originalPrice: '85.00',
    discountedPrice: '65.00',
  },
  {
    id: 6,
    name: 'Demonstration board',
    image: './images/demonstration-board.png',
    rating: 4,
    originalPrice: '40.00',
    discountedPrice: '35.00',
    new: true,
  },
];
